---
abstract: 'Simple object oriented system for Perl'
author:
  - 'Geovanny Junio <geovannyjs@gmail.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Soo
version: 0.0.2
x_generated_by_perl: v5.22.1
x_serialization_backend: 'YAML::Tiny version 1.69'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
